# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ansible-controller" do |vm1|
    vm1.vm.hostname = "ansible-controller"
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", type: "dhcp"
    vm1.vm.provider "virtualbox" do |vb|
  #    vb.gui = true
       vb.name = "ansible-controller"
       vb.memory = "1024"
    end
  end

  config.vm.define "target-machine1" do |vm2|
    vm2.vm.hostname = "target-machine1"
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.network "private_network", type: "dhcp"

    vm2.vm.provider "virtualbox" do |vb|
  #    vb.gui = true
       vb.name = "target-machine1"
       vb.memory = "1024"
    end

  end
end
